[project]
requires-python = ">=3.6"
name = "QMeQ-fork"
version = "1"

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cython",
    "numpy",
    "scipy"
]
build-backend = "setuptools.build_meta"
